### ISSUE TITLE
Registration : Phone number disappears after cliking get otp 

### ISSUE THREAD

**Issue by abhilla** [zite69/shop-cms#54] opened 2024-12-04 04:44 UTC
if user make a mistake by entering wrong OTP and validates then phone number disappears. User has to again enter phone number and will be doubtful to reenter 'old' right  OTP, Actually old otp works even if we type same phone number but user may click again on  'Get OTP' and second otp delivered but first OTP only works, This is confusing and not a smooth experience. 

Once the user entered hone number it has to stay there until user enter right otp.  

Nowadays, users are quite familiar with OTP process experience, so we need to make ours as a standardized process.
It has to behave like all other phone and mail otp interface.

**Comment by arunk** [comment] 2024-12-04 10:58
This seems to be a duplicate of issue #51 . Please create only single issues for single bugs or related bugs. Closing this bug, if there is any information unique inside this issue then please add it to 51.

**Closed by arunk** 2024-12-04 10:58 UTC
